# Inserts a blank line between shell prompts
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ïŒ§  â¯](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[ïŒ§  âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "[âš¡]ï¸(bold green) "
discharging_symbol = "ğŸ’€ "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[python]
symbol = "ğŸ "
pyenv_version_name = true

[directory]
format = "[ ğŸ“‚ $path]($style)[$read_only]($read_only_style) "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
#prefix = " ğŸ“‚ "

[hostname]
ssh_only = false
format = "[$hostname](bold green) "
#trim_at = ".companyname.com"
disabled = false

[username]
#format = "[$username](bold cyan)"
#style_user = "bold dimmed blue"
show_always = true

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "â‡¡ $count "
behind = "â‡£ $count "
deleted = "ğŸ—‘ $count "
diverged = "ï—º $count "
stashed = "ğŸ“¦ $count "
modified = "[ï­ $count ](yellow)"
staged = '[ï§ $count ](green)'
renamed = "ï‘š $count "
untracked = "ğŸ¤· â€$count "
style = "bold red"
